### ISSUE TITLE
Wolfsblvt's ToDo List

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/BlossomsPokemonGoManager#427]
This issue will stay open. I need to save my todo list somewhere where I can link issues, files and commits, so GitHub just makes sense *lol*.
Also, anyone can see what I am working on in that case :P 
# ToDos:
- [x] Fixing rename output (#424)
- [x] Checkout if location can be found by API (#423)
- [x] Column for PIDs (#417)
- [x] Auto-Increment number column (#302)
- [x] Re-Order columns to an order that makes sense
- [x] Rework Renaming pattern (new ones + all with two characters)
- [x] Colored Ratings in Table
- [x] Exception handling on outmost program position
- [x] Fix NullPointerException
- [x] Moves that got removed result in Rating higher than 100% (I think old moves are still used in the API)
- [x] Add Move Type columns
- [ ] Change Look and feel of program, especially table
- [ ] Change config class to Gson
- [ ] Fix breaking for saved ordering with non-existent column
- [ ] Add rename patterns via double-click
- [ ] Best Movesets for each Pokémon displayed (via button or something)
- [ ] Advanced Logger class
- [x] Save column order over sessions
- [ ] Make columns hideable
- [ ] Description for each column (#298)
- [ ] Providing ability to view capture location of Pokémon on Google Maps (via link)
- [ ] Maybe (Adding a feature where you could view a Google Maps map with all your caught Pokémon)

**Comment by BlackDragon381** [comment]
Please add:
- [ ] Sorting by several columns (by pressing Alt or Shift)
- [ ] Total list of transfer (now if start two transfer it's parallel process) or multi transfer support (all pokemons at a one time)
- [ ] The sign that it is not the first evolution
- [ ] Maximum length for pokemon name in rename window
- [ ] Filters for each columns
- [ ] Icons for each pokemon types
- [ ] The sign that it is not the last evolution

Or I should create an issue for each task?

**Comment by Wolfsblvt** [comment]
@BlackDragon381 

Sorting by several columns is already possible. Just sort by one, then the other and the previous sort is still there. So just apply them backwards. Makes sense. It is even saved for two columns, over the sessions.

Multi transfer will be part of the next update.

A column showing which evolution this is could work well, that's true.

Filters for each columns aka what columns you want to show and which not, or what values you want to show as rows? First is already on the list, second one is not considered until now.

Icons is already on the list.

**Comment by just-Addict** [comment]
Adding icons may draw unwanted attention. TPC/Niantic have been coming down hard on trackers that used icons with legal threats because images are protected. A better alternative would be to allow the user to add them from an external source like for instance is done in PokeSensor now

**Comment by Macgyver7th** [comment]
Hello Wolf,
    
        Looks like you have enough on that todo list, I was wondering if you had to have the free time to take a look at 'failed to get game data from the server #538'  I just added some more comments with a picture of trying to login.. Anyways thanks for taking a look at this and look forward to chatting with you on this issue.

**Comment by Wolfsblvt** [comment]
Thanks for reporting this and for using BlossomsPokemonGoManager. This project is no longer maintained and no longer works with current Pokémon Go services, so I’m closing all remaining issues as part of archiving it. Please do not use it with a live account or current credentials. See the [Disclaimer](https://github.com/Wolfsblvt/BlossomsPokemonGoManager#disclaimer) for details.

**Comment by Wolfsblvt** [comment]
Thanks for reporting this and for using the project. Blossoms Pokémon Go Manager is no longer maintained and no longer works with current Pokémon Go services, so I’m closing all remaining issues as part of archiving the repository. This avoids leaving a false impression that further development or support is planned.
